common: &common
  adapter: postgresql
  username: tim
  password: 

development:
  <<: *common
  database: snippets_development

test:
  <<: *common
  database: snippets_test

production:
  <<: *common
  database: snippets_production
